kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cert-manager-trust.name" . }}
  namespace: {{ .Values.app.trust.namespace }}
  labels:
{{ include "cert-manager-trust.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - "leases"
  verbs:
  - "get"
  - "create"
  - "update"
  - "watch"
  - "list"
